server:
  port: 8082
spring:
  application:
    name: example-consumer
  cloud:
    polaris:
      address: grpc://ds.com:8091
      discovery:
        enabled: true
      stat:
        enabled: true
        port: 18082
